### ISSUE TITLE
Demo Import Video Not Available 

### ISSUE THREAD

**Issue by MikeAngelino** [95mediawebsolutions/Clark-WP#1]
Hi guys, 

Clark theme was installed successfully and the demo import worked, but the pages and most of the sections are not visible. Is there a shortcode I need to add to the homepage or maybe I missed something. The video is not available.

Thank you

**Comment by 95mediawebsolutions** [comment]
Hi, Mike thank you for downloading the theme. The reason you are not getting the right result is that you are using the latest post as your front end. You need to go to settings->reading and change it from latest post to a static page and choose home for home page and blog for post page and everything should work fine. I will be writing a new update for the theme soon and sorry about the video missing let me know if that work.

**Comment by MikeAngelino** [comment]
Hi, thank you very much for the reply, I had tried that but something is wrong. I might have to start from scratch. the site is at miguel.cogitocode.org. 

Thank you

**Comment by 95mediawebsolutions** [comment]
Oh okay, that is weird, please send me your WP-ADMIN login details to support@95media.co.uk and I will have a look at it for you if you are okay with it. 

Regards.

**Comment by MikeAngelino** [comment]
I have sent you the details, don't worry too much about it, I can try rebuilding the DB or just use the HTML site which I have edited already. 

Thank you!

**Comment by 95mediawebsolutions** [comment]
I have fixed it now and everything should be working. However, what I found out was Post and Page Builder plugin was interfering with the theme having deactivated the plugin everything works fine. so I will advise you do the same if you plan to use the theme.

**Comment by MikeAngelino** [comment]
Awesome, thank you so much. I thought that might be the case.
Quick question, you are a freelancer or work for a company? I could add you
to my list of contacts and reach you when we get projects.

Regards,

**Comment by 95mediawebsolutions** [comment]
You're very welcome Mike. Yes, I am a freelancer and I will be open to any project you might have.

Regards
